[general]
import = [
"~/.config/alacritty/themes/themes/iris.toml",
"~/.config/alacritty/themes/themes/dark_pastels.toml",
"~/.config/alacritty/themes/themes/duskfox.toml",
"~/.config/alacritty/themes/themes/tokyo_night_storm.toml",
"~/.config/alacritty/themes/themes/hardhacker.toml",
"~/.config/alacritty/themes/themes/dark_pastels.toml",
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
blur = true

[font]
normal = { family = "monospace", style = "Regular" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
